version: '3.8'
services:
  db:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketplace
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"

  app2:
    build:
      context: ./authorization_service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - redis
    volumes:
      - ~/docker/redis:/redis-service/logs
    environment:
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379